name: "ds002r-fds"

project:
  type: website
  output-dir: _site
  resources: 
    - "handout/*"
  
website:
  title: "Foundations of Data Science in R"
  image: "images/st47s.png"
  favicon: "images/favicon.ico"
  site-url: https://ds002r-fds.netlify.app/
  repo-url: https://github.com/hardin47/ds002r-fds/
  page-navigation: true
  navbar:
    title: "Foundations of Data Science in R"
    description: |
      DS002R, Foundations of Data Science in R, Fall 2024
    background: success
    foreground: secondary
    search: true
    right:
      - text: "Syllabus"
        href: syllabus.qmd
      - text: "Class Notes"
        href: notes.qmd
      - text: "Clicker Q"
        href: clicker_study.qmd
      - text: "R tip"
        href: R-tip.qmd
      - text: "Project"
        menu: 
         - text: "semester mini-projects"
           href: project.html
         - text: "project 1 - website"
           href: project1.html
         - text: "project 2 - text analysis"
           href: project2.html
         - text: "project 3 - simulation analysis"
           href: project3.html
         - text: "project 4 - SQL"
           href: project4.html
         - text: "project 5 - project updates"
           href: project5.html
         - text: "Data Sources"
           href: https://hardin47.netlify.app/courses/data/
      - text: "GitHub"
        href: github.qmd
    logo: images/st47s.png
    logo-href: https://ds002r-fds.netlify.app/
  page-footer:
    left: |
      [{{< fa book >}}](https://hardin47.netlify.app/research/)
      <a href ="https://hardin47.netlify.app/resume.pdf" target = "_blank"><i class="fa-solid fa-bookmark"></i></a>
      <a href="mailto:jo.hardin@pomona.edu" target = "_blank"><i class="fa-solid fa-at"></i></a>
      <a href="https://scholar.google.com/citations?user=c5Y77poAAAAJ&hl=en" target = "_blank"><i class="fa-brands fa-google-scholar"></i></a>
      <a href="https://www.researchgate.net/scientific-contributions/Johanna-Hardin-9764530" target = "_blank"><i class="fa-brands fa-researchgate"></i></a>    
      <a href="https://github.com/hardin47" target = "_blank"><i class="fa-brands fa-github"></i></a>
      <a href="https://www.linkedin.com/in/jo-hardin-b91a4b55" target = "_blank"><i class="fa-brands fa-linkedin-in"></i></a>
    center:
      - text: |
          <br> © Jo Hardin, 2024 -- <a href = "mailto: jo.hardin@pomona.edu">jo.hardin@pomona.edu</a> -- <a href="https://hardin47.netlify.app/">https://hardin47.netlify.app/</a> <br> <br>
          DS002R -- Foundations of Data Science in R -- Pomona College <br>
license: "CC BY"
format:
  html:
    theme: 
      - cosmo
      - colors.scss



