---
title: "Endangered data"
description: |
  Information on important data that have become endangered or extinct recently.
format:
  html:
    html-math-method: katex
execute: 
  message: false
  warning: false
  echo: false
---


```{r}
library(tidyverse)
```


```{r}
#| echo: false

# fmt: skip

schedule <- tribble(
  ~`dataset`, ~`data last updated`, ~`description`, ~`info last updated` ,
  '<a href = "https://collegescorecard.ed.gov/data" target = "_blank">College Scorecard</a>', '
  6-10-2026' , 
  'Data on student completion, debt and repayment, earnings, and more. Large amount of missing data so as to make the data unusable. <a href = "https://www.naicu.edu/policy-advocacy/issue-briefs/college-scorecard/" target = "_blank">History of the College Scorecard</a>.',
  '8-29-2026',

  '<a href = "https://www.census.gov/programs-surveys/acs/data.html" target = "_blank">American Community Survey</a>', 
  '<a href = "https://www.census.gov/programs-surveys/acs/news/data-releases.html" target = "_blank">9-11-2025</a>' , 
  '<a href = "https://www.census.gov/programs-surveys/acs/about.html" target = "_blank">The American Community Survey (ACS)</a> is an ongoing survey that provides vital information on a yearly basis about <a href = "https://www.census.gov/programs-surveys/acs/guidance/subjects.html" target = "_blank">social, economic, housing, and demographic factors</a>. Information from the survey generates data that help inform how trillions of dollars in federal funds are distributed each year. As of <a href = "https://www.census.gov/programs-surveys/acs/news/updates.2026.html#form-dropdown-456855606" target = "_blank">August 6, 2026</a> the administration is banning any statistical representation of information (to avoid privacy violation) and is using coarsened information (e.g., "fewer than 50") instead. Additionally, from 2024 to 2025, approximately <a href = "https://www.govexec.com/workforce/2025/07/census-has-long-struggled-staffing-shortages-employees-say-trump-making-it-worse/406840/" target = "_blank">10% of the census workforce was laid off</a>.',
  '9-15-2026',


  '<a href = "https://ngmdb.usgs.gov/ngmdb/ngmdb_home.html" target = "_blank">National Geologic Map Database</a>', 
  '9-21-2026' , 
  '<a href = "https://ngmdb.usgs.gov/ngm-bin/ngm_compsearch.pl" target = "_blank">National Geologic Map Database (NGMD)</a> is set of maps created by the <a href = "https://en.wikipedia.org/wiki/United_States_Geological_Survey" target = "_blank">US Geological Survery (USGS)</a> to understand mineral, energy, and groundwater reserves; to track natural risks like earthquakes, landslides, sinkholes, and floods; to guid construction; and to understand millions of years of geological evolution. Major cuts to USGS have impact the agency&#39;s ability to create and sustain their maps and other databases. Organizations from the <a href = "https://esa.org/wp-content/uploads/2026/04/USGS-Coalition_Public-Statement_FY2027-PBR-Response_FINAL.pdf" target = "_blank">USGS Coalition</a> to the <a href = "https://thebaynet.com/usgs-faces-big-cuts-endangering-chesapeake-science/" target = "_blank">Chesapeake Bay Program</a> report some of the major impacts that the resulting cuts in funding will have.',
  '9-21-2026',

  '<a href = "https://www.bls.gov/cpi/data.htm" target = "_blank">Consumer Price Index</a>', 
  '9-11-2026' , 
  '<a href = "https://www.bls.gov/cpi/" target = "_blank">The Consumer Price Index (CPI)</a> is a measure of the average change over time in the prices paid by urban consumers for a market basket of consumer goods and services.CPI is collected by the Bureau of Labor Statistics (BLS) who <a href = "https://www.bls.gov/cpi/notices/2025/more-information-collection-reduction.htm" target = "_blank">suspended data collection</a> in 2025 in select areas (including Lincoln, NE, Provo, UT, and Buffalo, NY). CPI provides monthly snapshots of price changes to hundreds of products and <a href = "https://www.reuters.com/business/us-inflation-data-collection-hurt-by-trump-era-hiring-freeze-wsj-says-2025-06-04" target = "_blank"> provides a near-real-time estimate</a> of the state of inflation.',
  '9-30-2026',

  '<a href = "https://www.ers.usda.gov/topics/food-nutrition-assistance/food-security-in-the-us" target = "_blank">Food Security Supplement (FSS) to the Current Population Survey (CPS)</a>', 
  '12-31-2024' , 
  'In September 2025, the <a href = "https://www.fna.usda.gov/newsroom/usda-0219.25" target = "_blank"> USDA terminated</a> the FSS as "redundant, costly, politicized, and extraneous". <a href = "https://frac.org/blog/threats-to-food-security-data-why-the-redundancy-claim-doesnt-hold-up" target = "_blank">Historically</a>, failing to measure hunger allows policy makers to downplay growing hardship.',
  '10-05-2026'

)
```



```{r}
#| echo: false
#| column: body-outset
# can also use column: screen-inset also the entire page??
# can use column: page for the entire page
# can use column: body-outset to bleed outside the center column of text
schedule |>
  gt::gt() |>
  gt::fmt_markdown(columns = everything()) |>
  gt::cols_width(
    description ~ gt::pct(64),
    dataset ~ gt::pct(12),
    everything() ~ gt::pct(12)
  ) |>
  gt::tab_options(table.width = gt::pct(100))
```


