---
title: "Project 2"
description: |
  text analysis
format: html
---

### Overview

You will find a data set containing string data.  This could be newspaper articles, tweets, songs, plays, movie reviews, or anything else you can imagine.  Then you will answer questions of interest and tell a story about your data using string and regular expression skills you have developed.

Your analysis must contain the following elements:

- at least 3 `str_*()` functions
<!-- - at least 3 regular expressions -->
- at least 2 illustrative, well-labeled plots or tables
- a description of what insights can be gained from your plots and tables
- a reference / documentation of the data source.



### Some potential places to find text data

<!--

datasets with strings:



Shakespeare Dialogue: https://github.com/rfordatascience/tidytuesday/blob/master/data/2024/2024-09-17/readme.md

Netflix titles: https://github.com/rfordatascience/tidytuesday/blob/master/data/2021/2021-04-20/readme.md

synopses data frame for Broadway Weekly Grosses: https://github.com/rfordatascience/tidytuesday/blob/master/data/2020/2020-04-28/readme.md

Friends: friends <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-09-08/friends.csv')

(friends R package, too)

Federalist papers:  https://github.com/nicholasjhorton/FederalistPapers/

Load the package into R using

install.packages("remotes")
remotes::install_github("nicholasjhorton/FederalistPapers")

All of Emily Dickinson's poems:
https://github.com/Amherst-Statistics/DickinsonPoems

devtools::install_github("Amherst-Statistics/DickinsonPoems")

Every line of the office: https://www.kaggle.com/datasets/fabriziocominetti/the-office-lines

Obama tweets:

archived by the National Archives: https://www.obamalibrary.gov/digital-research-room/archived-white-house-websites-and-social-media

Read in the “Dear Abby” data underlying The Pudding’s [30 Years of American Anxieties article](https://pudding.cool/2018/11/dearabby/).


posts <- read_csv("https://raw.githubusercontent.com/the-pudding/data/master/dearabby/raw_da_qs.csv")


- [Other articles from The Pudding](https://github.com/the-pudding/data)
- NY Times headlines from the RTextTools package (see below)
- further analysis with the `bigspotify` data from class
- the options are endless -- be resourceful and creative!

```{r}
#| message: false
#| eval: false

library(RTextTools)  # may have to install first
data(NYTimes)
as_tibble(NYTimes)
```

-->


### Timeline

Mini-Project 2 must be submitted on Canvas (not Gradescope) by **11:59 PM on Wednesday October 2**.  Ideally, you will add a tab to your Quarto webpage for Mini-Project 2, then you can just submit the new page's URL. Alternatively, you may submit a Rendered pdf showing all code and output.