---
title: "Worksheet 5 - regular expressions II"
author: "Jo Hardin"
date: "January 12, 2023"
format: pdf
execute:
  echo: true
  warning: false
  message: false
---

```{r}
#| include: false
library(tidyverse)
library(DBI)
```



Your Name: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_   


Names of people you worked with:  \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_   

* Introduce yourself. Tell your group about one talk/performance/event/activity not related to your classes that you are looking forward to in the coming weeks.

* In the last year, have you had a somewhat extended conversation (maybe over lunch or coffee, maybe in an office hour) with one of your professors which was not directly related to a class that you were taking with them?


\medskip
\medskip

**Task:**

Consider the following R code: `gregexp(pattern, string)` where `pattern` refers to the row and `string` refers to the column in the following table.  For the first row and first column: `gregexpr("[0-9]{3,4}", "stat data sci 261")` would return location 15 and length 3.

In each corresponding table cell, write down the value that is returned (i.e., the location of the match(es) and the length of the match(es)) or `-1` if no match is found.


|              | "stat data sci 261" | "statistics" | "I love R!" | "January 12, 2024" |
|-------------|-----------------|----------------|-------------|-----------------|
| "[0-9]{3,4}" |  `r g <- gregexpr("[0-9]{3,4}", "stat data sci 261"); pos <- g[[1]][1]; length <- attr(g[[1]],'match.length'); paste0('pos: ', pos, ' length: ', length)` |              |             |                    |
|              |                 |              |             |                    |
| "[!,]"       |                 |              |             |                    |
|              |                 |              |             |                    |
| "st"         |                 |              |             |                    |
|              |                 |              |             |                    |
| "[A-Z]+"     |                 |              |             |                    |
|              |                 |              |             |                    |
| "stat*"      |                 |              |             |                    |
|              |                 |              |             |                    |

\newpage

**Solution:**

\footnotesize

|              | "stat data sci 261" | "statistics" |  "I love R!"  | "January 12, 2024" |
|--------------|-----------------|----------------|-----------------|-----------------------|
| "[0-9]{3,4}" | `r g <- gregexpr("[0-9]{3,4}", "stat data sci 261"); pos <- g[[1]][1]; length <- attr(g[[1]],'match.length'); paste0('pos: ', pos, ' length: ', length)` | `r g <- gregexpr("[0-9]{3,4}", "statistics"); pos <- g[[1]][1]; length <- attr(g[[1]],'match.length'); paste0('pos: ', pos, ' length: ', length)`| `r g <- gregexpr("[0-9]{3,4}", "I love R!"); pos <- g[[1]][1]; length <- attr(g[[1]],'match.length'); paste0('pos: ', pos, ' length: ', length)` |`r g <- gregexpr("[0-9]{3,4}", "January 12, 2024"); pos <- g[[1]][1]; length <- attr(g[[1]],'match.length'); paste0('pos: ', pos, ' length: ', length)`|
| "[!,]"       | `r g <- gregexpr("[!,]", "stat data sci 261"); pos <- g[[1]][1]; length <- attr(g[[1]],'match.length'); paste0('pos: ', pos, ' length: ', length)` | `r g <- gregexpr("[!,]", "statistics"); pos <- g[[1]][1]; length <- attr(g[[1]],'match.length'); paste0('pos: ', pos, ' length: ', length)`| `r g <- gregexpr("[!,]", "I love R!"); pos <- g[[1]][1]; length <- attr(g[[1]],'match.length'); paste0('pos: ', pos, ' length: ', length)` |`r g <- gregexpr("[!,]", "January 12, 2024"); pos <- g[[1]][1]; length <- attr(g[[1]],'match.length'); paste0('pos: ', pos, ' length: ', length)`| 
| "st"         |`r g <- gregexpr("st", "stat data sci 261"); pos <- g[[1]][1]; length <- attr(g[[1]],'match.length'); paste0('pos: ', pos, ' length: ', length)` | `r g <- gregexpr("st", "statistics"); pos <- g[[1]][1:2]; length <- attr(g[[1]],'match.length'); paste0('pos: ', pos, ' length: ', length)`| `r g <- gregexpr("st", "I love R!"); pos <- g[[1]][1]; length <- attr(g[[1]],'match.length'); paste0('pos: ', pos, ' length: ', length)` |`r g <- gregexpr("st", "January 12, 2024"); pos <- g[[1]][1]; length <- attr(g[[1]],'match.length'); paste0('pos: ', pos, ' length: ', length)`| 
| "[A-Z]+"     | `r g <- gregexpr("[A-Z]+", "stat data sci 261"); pos <- g[[1]][1]; length <- attr(g[[1]],'match.length'); paste0('pos: ', pos, ' length: ', length)` | `r g <- gregexpr("[A-Z]+", "statistics"); pos <- g[[1]][1]; length <- attr(g[[1]],'match.length'); paste0('pos: ', pos, ' length: ', length)`| `r g <- gregexpr("[A-Z]+", "I love R!"); pos <- g[[1]][1:2]; length <- attr(g[[1]],'match.length'); paste0('pos: ', pos, ' length: ', length)` |`r g <- gregexpr("[A-Z]+", "January 12, 2024"); pos <- g[[1]][1]; length <- attr(g[[1]],'match.length'); paste0('pos: ', pos, ' length: ', length)`| 
| "stat*"      |`r g <- gregexpr("stat*", "stat data sci 261"); pos <- g[[1]][1]; length <- attr(g[[1]],'match.length'); paste0('pos: ', pos, ' length: ', length)` | `r g <- gregexpr("stat*", "statistics"); pos <- g[[1]][1]; length <- attr(g[[1]],'match.length'); paste0('pos: ', pos, ' length: ', length)`| `r g <- gregexpr("stat*", "I love R!"); pos <- g[[1]][1]; length <- attr(g[[1]],'match.length'); paste0('pos: ', pos, ' length: ', length)` |`r g <- gregexpr("stat*", "January 12, 2024"); pos <- g[[1]][1]; length <- attr(g[[1]],'match.length'); paste0('pos: ', pos, ' length: ', length)`| 
